version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.keycloak.bom:keycloak-adapter-bom
    versions:
    - 12.0.2
    - 12.0.3
  - dependency-name: org.keycloak:keycloak-spring-boot-starter
    versions:
    - 12.0.2
    - 12.0.3
  - dependency-name: nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect
    versions:
    - 2.5.2
  - dependency-name: org.springframework.security.oauth:spring-security-oauth2
    versions:
    - 2.5.0.RELEASE
